CONF = ../../CONF
COMMON = ../../../COMMON

include $(CONF)/rules.make

cfiles = is.r
lib = lib.l

all: $(lib)

$(lib): $(cfiles)
	merge $^ >-$@

#######################################

is.r: sconf.h errorcodes.h debug.h is.h
