/*
 *    Defination of the Service Request Valuse for tms device driver
 */

#define		SS_Reset	200		/* Activates the IFC line on the IEC bus */
#define		SS_LisAd	201		/* Address the given device as Lisener */
#define		SS_TlkAd	202		/* Address the given device as Talker */
#define		SS_Trig		203		/* Send a Group Execute Trigger Command */
#define		SS_Time		204		/* Set Time-Out Value for Controller Read */
#define		SS_SRq		205		/* Generate a Service Request */
#define		SS_Command	206		/* Send Addressed or universal Command */
#define		SS_SSRq		207		/* Send signal if SRQ goes active */
#define		SS_EoR		208		/* Set 'End of Record' character */

/*
 *    Special Error Codes generated by the tms device driver
 */
 
#define		E_TmOut		0x3301	/* Time out error */
#define		E_NFree		0x3302	/* Output buffer not empty */
#define		E_EoIPend	0x3303	/* Present record not output yet */
#define		E_SetUp		0x3304	/* Ieee not set up correctly */
#define		E_BState	0x3305	/* Ieee in wrong state */
#define		E_IFC		0x3306  /* Aborted by IFC */
#define		E_NAcptr	0x3307	/* No Acceptor on IEC bus */


/*
 *		Addressed Command Group
 */
#define		GTL		0x01		/* Goto Local */
#define		SDC		0x04		/* Selected Device Clear */
#define		PPC		0x05		/* Parallel Poll Configure */
#define		GET		0x08		/* Group execute trigger */

/*
 *		Universal Command Group
 */
#define 	DCL		0x14		/* Device Clear */
#define 	SPE		0x18		/* Serial Poll Enable */
#define 	SPD		0x19		/* Serial Poll Disable */

/*
 *		Listener Address Group
 */
#define		LAG		0x20		/* Listener Address Group */
#define		UNL		0x3f		/* Unlisten */

/*
 *		Talker Address Group
 */
#define		TAG		0x40		/* Talker Address Group */
#define		UNT		0x5f		/* Untalk */

