#! /bin/sh
#\
exec emswish $0 $*

# $ZEL: pat_disp,v 1.1 2002/09/26 12:15:12 wuestner Exp $
# P. Wuestner 2002; Zentrallabor fuer Elektronik; Forschungszentrum Juelich
#

# Vorbereitung fuer 'autoload' von Prozeduren; die Variable local_library
# muss an die konkrete Installation angepasst werden.
if [info exists env(EMSTCL_HOME)] {
  set local_library $env(EMSTCL_HOME)/pat_disp
  set common_library $env(EMSTCL_HOME)/common
} else {
  set local_library /usr/local/ems/lib/pat_disp
  set common_library /usr/local/ems/lib/common
}
lappend auto_path $local_library $common_library

# Kommandozeilenargumente verarbeiten
process_args
set global_verbose [info exists namedarg(verbose)]
if {$global_verbose} printargs

if [info exists namedarg(help)] {
  printhelp
  exit
}

bind Entry <Delete> {
       tkEntryBackspace %W
}
#bind Entry <apLineDel> {
#       if [%W selection present] {
#      %W delete sel.first sel.last
#  } else {
#      %W delete insert
#  }
#}
wm withdraw .
set_options
set maintitle TriggerPattern
if [regexp #.* [winfo name .] number] {
  append maintitle $number
}
wm title . $maintitle
wm maxsize . 10000 10000

tk_focusFollowsMouse
set tcl_precision 17

# proc namespacedummies is called in order to load bgerror and all
#   procedures in namespaces
namespacedummies

set global_display [display_name]
set global_setupfile(default) [setupfile_name $global_display]

if [info exists namedarg(setup)] {
  set num_setup_files [llength [glob -nocomplain -- $namedarg(setup)]]
  if {$num_setup_files!=1} {
    if {$num_setup_files==0} {
      puts "no file $namedarg(setup)"
    } else {
      puts "filename $namedarg(setup) ambigous"
    }
  exit
  }
  set global_setupfile(restored) $namedarg(setup)
  set global_setupfile(save) $namedarg(setup)
  set global_setupfile(use_default) 0
} else {
  set global_setupfile(restored) [find_setupfile $global_setupfile(default) $global_display ~/patrc]
  set global_setupfile(save) $global_setupfile(default)
  set global_setupfile(use_default) 1
}
if {$global_setupfile(restored)!=""} {
  restore_setup $global_setupfile(restored)
}

# und, wenn noetig, Setup vervollstaendigen
correct_setup
use_args

start_gui
start_loop

###############################################################################
###############################################################################
