#! /bin/sh
#\
exec emswish $0 $*

# Vorbereitung fuer 'autoload' von Prozeduren; die Variable scaler_library
# muss an die konkrete Installation angepasst werden.
if [info exists env(EMSTCL_HOME)] {
  set scaler_library $env(EMSTCL_HOME)/scaler_anke
  set common_library $env(EMSTCL_HOME)/common
} else {
  set scaler_library /usr/local/ems/lib/scaler_anke
  set common_library /usr/local/ems/lib/common
}
lappend auto_path $scaler_library $common_library

# readonly attribute for "entry"
if {[info tclversion]>8.3} {
    set entry_ro {readonly}
} else {
    set entry_ro {disabled}
}

# Kommandozeilenargumente verarbeiten
process_args
set global_verbose [info exists namedarg(verbose)]
if {$global_verbose} printargs

if [info exists namedarg(help)] {
  printhelp
  exit
}

bind Entry <Delete> {
       tkEntryBackspace %W
}
#bind Entry <apLineDel> {
#       if [%W selection present] {
#      %W delete sel.first sel.last
#  } else {
#      %W delete insert
#  }
#}
wm withdraw .
set_options
set maintitle Scaler
if [regexp #.* [winfo name .] number] {
  append maintitle $number
}
wm title . $maintitle
wm maxsize . 10000 10000

tk_focusFollowsMouse
set tcl_precision 17

set global_display [display_name]
set global_setupfile(default) [setupfile_name $global_display]

if [info exists namedarg(setup)] {
  set num_setup_files [llength [glob -nocomplain -- $namedarg(setup)]]
  if {$num_setup_files!=1} {
    if {$num_setup_files==0} {
      puts "no file $namedarg(setup)"
    } else {
      puts "filename $namedarg(setup) ambigous"
    }
  exit
  }
  set global_setupfile(restored) $namedarg(setup)
  set global_setupfile(save) $namedarg(setup)
  set global_setupfile(use_default) 0
} else {
  set global_setupfile(restored) [find_setupfile $global_setupfile(default) $global_display ~/scalerrc]
  set global_setupfile(save) $global_setupfile(default)
  set global_setupfile(use_default) 1
}
if {$global_setupfile(restored)!=""} {
  restore_setup $global_setupfile(restored)
}

# und, wenn noetig, Setup vervollstaendigen
correct_setup
use_args

# proc dummytool is called in order to load bgerror
dummytool

# User-Interface starten oder im Verborgenen arbeiten
init_output Scaler_log
set global_running(graphical_display) 0
set global_running(numerical_display) 0
set global_loop_running 0
if {$global_setup(use_gui)} {
  start_gui
} else {
  if {[loop_start]<0} exit
}

###############################################################################
###############################################################################
