CONF = ../../CONF
COMMON = ../../../COMMON

include $(COMMON)/rules.make

cfiles = chi_ext_trigger.r immerpuls.r pulsertrigger.r

all: lib.l

lib.l: $(cfiles)
	merge $^ >-$@

#############################################

$(cfiles): errorcodes.h
signaltrigger.r: ../../OBJECTS/VAR/variables.h
