# Generated automatically from Makefile.in by configure.
# lowlevel/vicvsb/Makefile.in
# $ZEL: Makefile.in,v 1.5 2007/09/17 00:35:51 wuestner Exp $

CONF = ../../conf

include $(CONF)/rules.make
include $(CONF)/config.make

ofiles = vicrawlib.o

all: lib.a

lib.a: $(ofiles)
	ar rslc $@ $^

######################################################

