CONF = ../../../CONF
COMMON = ../../../../COMMON

include $(COMMON)/rules.make

cfiles = C_NE526.r

all: lib.l

lib.l: $(cfiles)
	merge $^ >-lib.l

#############################################################################

$(cfiles): errorcodes.h modultypes.h ../../../LOWLEVEL/VME/vme.h \
           ../../../OBJECTS/VAR/variables.h $(COMMON)/debug.h \
          $(CONF)/sconf.h 
