CONF = ../../../CONF
COMMON = ../../../../COMMON

include $(COMMON)/rules.make

cfiles = c219.r

all: lib.l

lib.l: $(cfiles)
	merge $^ >-$@

#############################################

$(cfiles): errorcodes.h
#c219.r: ../../../OBJECTS/VAR/variables.h
