dnl ***************************************************************************
dnl                                                                           *
dnl intmsgtypes.inc                                                           *
dnl                                                                           *
dnl 08.06.94                                                                  *
dnl                                                                           *
dnl ULTRIX/OSF1                                                               *
dnl                                                                           *
dnl **************************************************************************/

Intmsg(Nothing)
Intmsg(ClientIdent)
Intmsg(Open)
Intmsg(Close)
Intmsg(OpenVED)
Intmsg(CloseVED)
Intmsg(GetHandle)
Intmsg(GetName)
Intmsg(SetUnsolicited)
Intmsg(SetExitCommu)
version(4)

dnl **************************************************************************/
dnl **************************************************************************/
