CONF = ../../CONF
COMMON = ../../../COMMON

include $(COMMON)/rules.make

cfiles = ext_change.r

all: lib.l

lib.l: $(cfiles)
	merge $^ >-$@

#############################################

$(cfiles): errorcodes.h
