#!/bin/sh

rm count
find $1 -name '*.m4' -type f -exec linecount.sh {} \;
find $1 -name '*.c' -type f -exec linecount.sh {} \;
find $1 -name '*.h' -type f -exec linecount.sh {} \;
find $1 -name '*.cc' -type f -exec linecount.sh {} \;
find $1 -name '*.hxx' -type f -exec linecount.sh {} \;
find $1 -name '*.inc' -type f -exec linecount.sh {} \;
find $1 -name '[mM]akefile*' -type f -exec linecount.sh {} \;
find $1 -name '*.tcl' -type f -exec linecount.sh {} \;

echo total count: `cat count`
